version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "hello build"
      - run: npm i jest
      - run: npx jest 
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "hello test"
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
        requires:
          - build
      - build
      