version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "hello world2"
      - run: npm i -g jest
      - run: jest .