version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo "hello world2"
      - run: npm i jest
      - run: npx jest .